services:
  image: mongodb
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    env_file:
      - ./youapps/youapp/.env
    volumes:
      - .:/src/app
      - /src/app/node_modules
  rabbitmq:s
    image: rabbitmq
    ports:
      - '5672:5672'
  db:
      image: mongo:latest
      environment:
        - MONGODB_DATABASE="youapp"
      ports:
        - 27017:27017